spring:
  application:
    name: tramos
  datasource:
    url: jdbc:postgresql://localhost:6434/tramos_db
    username: tramos
    password: tramos
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  clients:
    camiones:
        url: http://localhost:8093/api/camiones
    envios:
        url: http://localhost:8095/api/envios
    ubicaciones:
        url: http://localhost:8094/api/ubicaciones
    osrm:
        uri-template: /route/v1/driving/{origen};{destino}?overview=false

server:
  port: 8092

#security:
#    oauth2:
#        resourceserver:
#            jwt:
#                issuer-uri: http://keycloak:8081/realms/tpi-backend

springdoc:
  swagger-ui:
    path: /swagger-ui.html
