spring:
  application:
    name: tramos
  datasource:
    url: jdbc:postgresql://localhost:6434/tramos_db
    username: tramos
    password: tramos
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  clients:
    usuarios:
        url: http://localhost:8090/api/usuarios
    camiones:
        url: http://localhost:8093/api/camiones
    envios:
        url: http://localhost:8095/api/envios
    ubicaciones:
        url: http://localhost:8094/api/ubicaciones
    contenedores:
        url: http://localhost:8091/api/contenedores
    osrm:
        uri-template: /route/v1/driving/{origen};{destino}?overview=false

server:
  port: 8092

springdoc:
  swagger-ui:
    path: /swagger-ui.html
