spring:
  application:
    name: camiones
  datasource:
    url: jdbc:postgresql://localhost:6435/camiones_db
    username: camiones
    password: camiones
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  clients:
      usuarios:
          url: http://localhost:8090/api/usuarios

server:
  port: 8093

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
    # 1. Referencia al archivo de configuración de Logback (Cumple TPI Paso 3)
    # Le dice a Spring Boot que use este archivo para la configuración avanzada.
    config: classpath:logback-spring.xml

    # 2. Definición de la ruta del archivo (usada por logback-spring.xml)
    file:
        # Ajustado para tu microservicio de camiones
        name: logs/microservicio-camiones.log # Cumple TPI Paso 3

    # 3. Definición de Niveles de Log (Cumple TPI Paso 2)
    level:
        # Nivel por defecto para todo (INFO)
        root: INFO

        # Nivel específico para TU código (DEBUG para diagnóstico)
        # ¡Ajustado al paquete de tus clases "camiones"!
        backend.grupo130.camiones: DEBUG

        # Reducir el "ruido" de librerías comunes
        org.springframework: INFO
        org.hibernate.SQL: WARN # Ocultar las queries de Hibernate, salvo que sean WARN
        org.hibernate.type.descriptor.sql: WARN
