spring:
  application:
    name: contenedores
  datasource:
    url: jdbc:postgresql://localhost:6433/contenedores_db
    username: contenedores
    password: contenedores
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  clients:
    usuarios:
      url: http://localhost:8090/api/usuarios

server:
    port: 8091

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
    # 1. Referencia al archivo de configuración de Logback (Paso 3)
    # Spring Boot buscará este archivo para aplicar la configuración de rotación.
    config: classpath:logback-spring.xml

    # 2. Definición de la ruta del archivo (usada por logback-spring.xml)
    file:
        # Ajustado para este microservicio
        name: logs/microservicio-contenedores.log # Cumple TPI Paso 3

    # 3. Definición de Niveles de Log (Cumple TPI Paso 2)
    level:
        # Nivel por defecto para todo (INFO)
        root: INFO

        # Nivel específico para NUESTRO código (DEBUG para diagnóstico)
        # Ajustado al paquete de tus clases
        backend.grupo130.contenedores: DEBUG

        # Reducir el "ruido" de librerías comunes en producción
        org.springframework: INFO
        org.hibernate.SQL: WARN # Ocultar las queries de Hibernate, salvo que sean WARN
        org.hibernate.type.descriptor.sql: WARN
