spring:
    application:
        name: contenedores
    datasource:
        url: jdbc:postgresql://localhost:6433/contenedores_db
        username: contenedores
        password: contenedores
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    clients:
        usuarios:
            url: http://localhost:8090/api/usuarios
    cloud:
        openfeign:
            httpclient:
                hc5:
                    enabled: true

server:
    port: 8091

springdoc:
    swagger-ui:
        path: /swagger-ui.html

logging:
    config: classpath:logback-spring.xml

    level:
        root: INFO
        backend.grupo130: DEBUG
        org.springframework: INFO
        org.hibernate: WARN

management:
    tracing:
        sampling:
            probability: 1.0
