spring:
  application:
    name: ubicaciones
  datasource:
    url: jdbc:postgresql://localhost:6436/ubicaciones_db
    username: ubicaciones
    password: ubicaciones
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8094

#security:
#    oauth2:
#        resourceserver:
#            jwt:
#                issuer-uri: http://keycloak:8081/realms/tpi-backend

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# PASO 1: Configurar Niveles
logging:
    level:
        # Nivel raíz por defecto. Capturará INFO y superior (WARN, ERROR) de todas las librerías.
        root: INFO
        # Nivel específico para nuestro código. Queremos ver DEBUG y superior.
        backend.grupo130.ubicaciones: DEBUG
        # Opcional: Reducir el "ruido" de Spring y Hibernate en los logs
        org.springframework: INFO
        org.hibernate: INFO

# Configuración de persistencia y rotación de archivos
# Se delega a logback-spring.xml para control avanzado (Paso 3 y 4)
# Spring Boot buscará este archivo automáticamente.
logging.config: classpath:logback-spring.xml
