spring:
  application:
    name: ubicaciones
  datasource:
    url: jdbc:postgresql://localhost:6436/ubicaciones_db
    username: ubicaciones
    password: ubicaciones
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8094

#security:
#    oauth2:
#        resourceserver:
#            jwt:
#                issuer-uri: http://keycloak:8081/realms/tpi-backend

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
    # 1. Le dice a Spring que use el archivo XML
    config: classpath:logback-spring.xml

    # 2. Define los niveles
    level:
        root: INFO
        backend.grupo130: DEBUG # O el nivel que quieras para tu c√≥digo
        org.springframework: INFO
        org.hibernate: WARN
