spring:
  application:
    name: usuarios
  datasource:
    url: jdbc:postgresql://localhost:6432/usuarios_db
    username: usuarios
    password: usuarios
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

keycloak:
    server-url: http://localhost:8080
    realm: TPI-Backend
    client-id: usuarios-ms
    client-secret: z7wA4QiRm1vteC2uPFXIVjVfnLbi7BDG

server:
  port: 8090

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
    # 1. Le dice a Spring que use el archivo XML
    config: classpath:logback-spring.xml

    # 2. Define los niveles
    level:
        root: INFO
        backend.grupo130: DEBUG # O el nivel que quieras para tu c√≥digo
        org.springframework: INFO
        org.hibernate: WARN

management:
    tracing:
        sampling:
            probability: 1.0
